name: Feature Request / 功能建议
description: Suggest an idea for this project / 为项目提出建议
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting an idea!
        ## 感谢你的建议！

  - type: textarea
    id: problem
    attributes:
      label: Related Problem / 相关问题
      description: Is your feature request related to a problem? Please describe / 你的功能请求是否与某个问题相关？请描述
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired Solution / 期望方案
      description: A clear and concise description of what you want to happen / 清晰简洁地描述你希望发生什么
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / 替代方案
      description: What alternatives have you considered? / 你考虑过哪些替代方案？

  - type: textarea
    id: context
    attributes:
      label: Additional Context / 补充信息
      description: Add any other context, screenshots, or mockups here / 添加其他上下文、截图或原型图
